services:
  - type: web
    name: library-management
    runtime: java
    plan: free
    region: singapore
    branch: main
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/library-management.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: 17